services:
    alfredoramos.hcaptcha.helper:
        class: alfredoramos\hcaptcha\includes\helper
        arguments:
            - '@language'

    alfredoramos.hcaptcha.captcha.hcaptcha:
        class: alfredoramos\hcaptcha\captcha\plugins\hcaptcha
        arguments:
            - '@config'
            - '@user'
            - '@request'
            - '@template'
            - '@language'
            - '@log'
            - '@alfredoramos.hcaptcha.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
        calls:
            - ['set_name', ['alfredoramos.hcaptcha.captcha.hcaptcha']]
        tags:
            - { name: captcha.plugins }
